version: '3'
services:
  nextjs:
    container_name: vashaobuv22_nextjs
    build: ./
    volumes:
      - shoes_photos:/usr/app/public/shoes_photos
      - stores_photos:/usr/app/public/stores_photos
      - banners:/usr/app/public/banners
      - data:/usr/app/data
      - logs:/usr/app/logs
  nginx: 
    container_name: vashaobuv22_nginx
    build: ./nginx
    volumes:
      - shoes_photos:/usr/app/public/shoes_photos
      - stores_photos:/usr/app/public/stores_photos
      - banners:/usr/app/public/banners
    ports:
      - 80:80
volumes:
  shoes_photos:
  stores_photos:
  banners:
  data:
  logs:
