version: '3'
services:
  nextjs:
    build: ./
    volumes:
      - public:/usr/app/public
      - data:/usr/app/data
      - logs:/usr/app/logs
  nginx: 
    build: ./nginx
    volumes:
      - public:/usr/app/public
    ports:
      - 80:80
volumes:
  public:
  data:
  logs:
