version: '3'
services:
  nextjs:
    build: ./
    volumes:
      - public:/usr/app/public
  nginx: 
    build: ./nginx
    volumes:
      - public:/usr/app/public
    ports:
      - 80:80
volumes:
  public:
